apiVersion: apps/v1
kind: Deployment
metadata:
  name: abn-pfm-ms
  namespace: dev
  labels:
    run: abn-pfm-ms
spec:
  selector:
    matchLabels:
      run: abn-pfm-ms
  replicas: 1
  template:
    metadata:
      labels:
        run: abn-pfm-ms
    spec:
      containers:
        - name: abn-pfm-ms
          image: integration-ms:0.0.1
          imagePullPolicy: Always
          env:
            - name: ABN_API_KEY
              value: "sQZJArRxjjHMe9y2"
            - name: CLIENT_INFORMATION_ATTRIBUTES
              value: "clientType,clientNumber,accountNumber,subAccountNumber"
            - name: PRODUCT_INFORMATION_ATTRIBUTES
              value: "exchangeCode,productGroupCode,symbol,expirationDate"
          ports:
            - containerPort: 8085
          resources:
            limits:
              cpu: 500m
              memory: 750Mi
            requests:
              cpu: 250m
              memory: 500Mi
          livenessProbe:
            failureThreshold: 7
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: abn-pfm-ms-ip
  namespace: dev
  labels:
    run: abn-pfm-ms
spec:
  type: ClusterIP
  ports:
    - port: 8085
      name: http
  selector:
    run: abn-pfm-ms